project:
  type: website
  output-dir: docs
  preview:
    port: 4200
    browser: true
    navigate: true

website:
  title: "MEEM"
  description: "Measure of Emotional Episodes with Music (MEEM)"
  repo-url: https://github.com/tuomaseerola/MIMEE/
#  repo-actions: [source, edit, issue]
  site-url: "https://tuomaseerola.github.io/MEEM/"
  search: true
  navbar:
    left:
      - href: index.qmd
#        text: Home
      - icon: github
        href: https://github.com/tuomaseerola/MEEM/
        aria-label: GitHub
  page-navigation: true
  back-to-top-navigation: true
  sidebar:
    - title: "Home"
      style: "floating"
      collapse-level: 3
      align: left
      contents: 
          - text: "Home"
            href: index.qmd
          - section: "Experiment"
            contents:
                - exp1/preprocessing.qmd
                - exp1/CFA_direct.qmd
                - exp1/measurement_invariance.qmd
                - exp2/describe_data.qmd
                - exp2/CFA.qmd
                - exp2/higher_order_structure.qmd
                - exp2/vignette_to_emotions.qmd
  page-footer: 
    right: 
      - icon: github
        href: https://github.com/tuomaseerola/MEEM/
format:
  html:
    theme: materia # zephyr, lumen, pulse, materia, yeti, zephyr
    css: styles.css
    toc: false
    page-layout: full
