---
title: "Measure of Emotional Episodes with Music (MEEM): Development and psychometric evaluation of a modular instrument"
author:
  - name: Connor Kirts
    orcid: 0009-0009-7207-6884
    email: connor.kirts@durham.ac.uk
    affiliations:
      - name: Durham University, UK
  - name: Suvi Saarikallio
    orcid: 0000-0002-4647-8048
    email: suvi.saarikallio@jyu.fi
    affiliations:
      - name: University of Jyväskylä, Finland
  - name: Tuomas Eerola
    orcid: 0000-0002-2896-929X
    email: tuomas.eerola@durham.ac.uk
    affiliations:
      - name: Durham University, UK
date: 01-06-2026
title-block-style: default
---

This repository offers data and analyses related to the study titled "Measure of Emotional Episodes with Music (MEEM): development and psychometric evaluation of a modular instrument, (submitted). This is scale development for an instrument to measure a emotional episodes related to music ([Eerola, Kirts & Saarikallio, 2025](https://doi.org/10.1177/03057356241279763)) that has been already developed through the content validity steps [Kirts et al., in press](https://tuomaseerola.github.io/MIMEE/).

The public-facing version of this repository is available at
[https://tuomaseerola.github.io/MEEM/](https://tuomaseerola.github.io/MEEM/). 

These are the main analytical operations carried out in the study in Experiments 1 and 2.

## Experiment 1

- [preprocessing](exp1/preprocessing.qmd) gets all the data, reports reliability, and visualises the item ratings.

<!-- - [EFA_first](EFA_first.qmd) carries out exploratory factor analyses (NOT NEEDED). -->

<!-- - [CFA_after_EFA](CFA_after_EFA.qmd) contains full items analysis and 4 and 3 best item analyses (just for EDR now). (NOT NEEDED) -->

- [CFA_direct](exp1/CFA_direct.qmd) contains full items analysis and 4 and 3 best item analyses.

<!-- - [Multilevel CFA](multilevel_CFA.qmd) reports 3 different ways of assessing the factor structures (CFA with Robust SE for participant repetitions, CFA de-meaned across vignettes, and multi-level CFA). -->

<!-- - [Multilevel CFA optimised](multilevel_CFA_alt.qmd) which contains one analysis with two weak items deleted and one with dummy coded vignettes. -->

- [measurement_invariance](exp1/measurement_invariance.qmd) reports configural, metric, and scalar invariance for the CFA participant-clustered robust SE models.

<!-- - [Bayesian multi-level CFA](bayesian_multi-level_CFA.qmd) (NOT NEEDED) -->



## Experiment 2

1. [describe_data](exp2/describe_data.qmd) summarises participant-level data (removal of low consistency participants, display demographics, visualise mean item ratings across vignettes). &check;

2. [CFA](exp2/CFA.qmd) reports CFA model fits, measurement invariance, and discriminant fit indices for each construct. Also displays the model summaries (loadings) together with means and standard deviations of the items. &check;

3. [higher_order_structure](exp2/higher_order_structure.qmd) tests higher order structures. Also reports construct reliability measures and discriminant validity tests for the models. &check;

4. [vignette_to_emotions](exp2/vignette_to_emotions.qmd) contains summary and construct validity with GEMIAC and HAAS scales. &check;



